### PR TITLE
Updated function and phpDoc to type mixed

### PR DESCRIPTION
**Pull request by insign**

### CODE REVIEW

**Comment by hexydec** [comment]
Thank you for contributing, I have merged your PR.  Yes I have been meaning to push another release of HTMLDoc with updated dependencies, which I have now done.

Please update HTMLDoc to version 1.2.1 which has been tested on PHP 8.

**Comment by insign** [comment]
The problem still exists, as I said, I think you need to publish a new tag.

**Comment by hexydec** [comment]
Apologies, I hadn't updated the tags in the composer file. All good now?

**Comment by insign** [comment]
Yes, thank you.

Em sáb., 29 de mai. de 2021 09:27, Will Earp ***@***.***>
escreveu:

**Pull request merged**
